return {
  tuplets={
    "arm-android",
    "arm64-android", "x86-android", "x64-android"
  },
  android={
    ndk_home='/data/AndroidSdk/ndk/23.1.7779620',
    ndk_api=23
  },
  dependencies={
    "lz4",
    "libffi",
    {
      name="rocksdb",
      version="latest",
      configure_options={
        ROCKSDB_LITE="ON",
        WITH_GFLAGS="OFF",
        WITH_LIBURING="OFF",
        WITH_IOSTATS_CONTEXT="OFF",
        WITH_PERF_CONTEXT="OFF",
        WITH_BENCHMARK_TOOLS="OFF",
        WITH_TESTS="OFF",
        WITH_ALL_TESTS="OFF",
        WITH_TOOLS="OFF",
        WITH_CORE_TOOLS="OFF",
        WITH_LZ4="ON",
      }
    },
  },
  export={
    {
      type='prefab',
      name='spdlog',
      modules={'spdlog', 'fmt'},
      min_sdk=23,
      target_sdk=31,
      maven=true,
    }
  }
}
